#!/bin/bash
echo "STARTING A SCRIPT FOR THE DEMO"
touch "/tmp/firstfile"
touch "/tmp/secondfile"
echo "TWO FILES HAS BEEN CREATED"
touch "/tmp/thirdfile"
touch "/tmp/fourthfile"
echo "SCRIPT HAS BEEN COMPLETED SUCCESSFULLY"
touch "/tmp/one"
touch "/tmp/two"
touch "/tmp/three"
echo "Pooling scm"
touch "/tmp/testone"
touch "/tmp/testtwo"
echo "All done, you can go for a tea now"
